name: Build & Release ZIP on tag

permissions:
  contents: write # <-- necessario per creare la release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Read version from plugin header
        id: version
        run: |
          VERSION=$(grep "Version:" billiard-scoreboard/billiard-scoreboard.php | head -1 | awk '{print $3}')
          if [ -z "$VERSION" ]; then
            echo "Version not found in plugin header"; exit 1
          fi
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "Detected version: $VERSION"

      - name: Zip plugin folder
        run: |
          zip -r "billiard-scoreboard-${{ steps.version.outputs.version }}.zip" billiard-scoreboard \
            -x "billiard-scoreboard/.git/*" "billiard-scoreboard/node_modules/*" "billiard-scoreboard/vendor/*"

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: "billiard-scoreboard-${{ steps.version.outputs.version }}.zip"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
